[jupiter.server.http]
    port = 8080
    host = "0.0.0.0"
    mode = "release"
[jupiter.server.grpc]
    port = 20102

[jupiter.etcdv3.default]
     endpoints=["172.17.22.140:2379"]
     secure = false

[jupiter.registry.bj01]
     configKey="jupiter.etcdv3.default"
     timeout = "1s"
# [jupiter.registry.bj02]
#     configKey="jupiter.etcdv3.default"
#     timeout = "1s"
[jupiter.cron.demo]
    immediatelyRun = false
    concurrentDelay = 5
    withSeconds = true
[jupiter.mysql.test]
    connMaxLifetime = "300s"
    debug = true
    dsn = "root:123456@tcp(172.20.99.13:3306)/db_apiserver?charset=utf8&parseTime=True&loc=Local"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100
    disableTrace = true
    disableMetric = true
# [jupiter.trace.jaeger]
#     enableRPCMetrics = false
#     [jupiter.trace.jaeger.sampler]
#         type = "const"
#         param = 0.001